fixup CVE-2023-4610
commit 1d843fe7b350 ("Update CVE-2023-4610") updated CVE-2023-4610
but there is type. We need "mainline".

Without this patch, we will get below error.

Traceback (most recent call last):
  File "./scripts/report_affected.py", line 187, in <module>
    main(args.git_repo, remotes, args.only_fixed_upstream,
  File "./scripts/report_affected.py", line 119, in main
    if kernel_sec.issue.affects_branch(
  File "/opt/disk_cd/morimoto/cip-kernel-sec/scripts/kernel_sec/issue.py", line 346, in affects_branch
    for commit in introduced['mainline']:
KeyError: 'mainline'

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>