fixup CVE-2023-4610
commit 1d843fe7b350 ("Update CVE-2023-4610") updated CVE-2023-4610
but there is type. We need "mainline".

Without this patch, we will get below error.

Traceback (most recent call last)a
>>> snip <<<
KeyError: 'mainline'

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>